# Generated by Django 5.2.1 on 2025-06-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("written_by", models.CharField(max_length=30)),
                ("quote", models.CharField(max_length=256)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
